### ISSUE TITLE
prestige-frontend never stops

### ISSUE THREAD

**Issue by laurent-simon** [sharat87/prestige#9]
When using the `make stop` command, or from the supervisor interface, the frontend server is never stopped. The corresponding Node server is still running and is usable on port 3040. No errors are reported. 

Initial process tree:

```txt
/sbin/init
 \_ npm exec parcel serve src/index.html --dist-dir dist-serve --port 3040
     \_ sh -c parcel "serve" "src\index.html" ""--dist-dir" "dist-serve" "--port" "3040"
         \_ node ~/prestige/frontend/node_modules/.bin/parcel serve src/index.html --dist-dir dist-serve --port 3040
             \_ ...
```

Same process tree after `make stop` :

```txt
/sbin/init
  \_ node ~/prestige/frontend/node_modules/.bin/parcel serve src/index.html --dist-dir dist-serve --port 3040
      \_ ...
```

The Node server lose its parent process and stay has a detached standalone process.

To restore the initial state, it must be killed manually. If it is not done, then on subsequent restart attempts:

* The front end startup fail on : `Error: Port "3040" could not be used`.
* It is reported as stopped on the supervisor interface.
* But, Prestige works perfectly : the old process is still serving on port 3040...

### Environment

Node : 16.6.0
Python: 3.8.10
OS: Kubuntu 20.10
Prestige:  d7be7e0

**Comment by sharat87** [comment]
Interesting! I'm running macOS and I can't reproduce this. For me, `make stop` or stopping it from the supervisor interface stops the frontend process and releases the port almost immediately. I'm wondering if this is a Linux-only problem.

Taking a second look though, I can imagine why this might be happening, and I'm surprised this isn't happening on macOS. Would it be possible for you to change the `command` for `prestige-frontend` in the `supervisord.conf` ([line 63](https://github.com/sharat87/prestige/blob/master/supervisord.conf#L63)) to the following and see if that resolves it? If not, I'll spend some time testing this on a Kubuntu VM this weekend to investigate further.

```
command=%(here)s/frontend/node_modules/.bin/parcel serve src/index.html --dist-dir dist-serve --port 3040
```

The change we are making is instead of having `npx` invoke a child process with `parcel`, we invoke `parcel` directly, so there shouldn't be a child process. Supervisor cannot stop child processes, its a documented limitation unfortunately.

**Comment by laurent-simon** [comment]
Perfect, now it works as expected.
